/**
 * nostr_core.h - C bindings for Nostr client library
 * 
 * This library provides NIP-17 private direct messaging for libpurple plugins.
 * 
 * Thread Safety:
 *   - All functions must be called from the main thread (GLib main loop)
 *   - The client uses internal async operations but callbacks are delivered
 *     synchronously when nostr_client_process_events() is called
 * 
 * Memory Management:
 *   - All *_free() functions must be called to release resources
 *   - Strings returned by the library are owned by the caller and must be freed
 *     with nostr_string_free()
 */


#ifndef NOSTR_CORE_H
#define NOSTR_CORE_H

/* Generated with cbindgen:0.28.0 */

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace  {
#endif  // __cplusplus

/**
 * Success
 */
#define nostr_NOSTR_OK 0

/**
 * Invalid argument (null pointer, invalid format, etc.)
 */
#define nostr_NOSTR_ERR_INVALID_ARG -1

/**
 * Network/relay error
 */
#define nostr_NOSTR_ERR_NETWORK -2

/**
 * Cryptographic error
 */
#define nostr_NOSTR_ERR_CRYPTO -3

/**
 * Internal error
 */
#define nostr_NOSTR_ERR_INTERNAL -4

/**
 * Opaque handle to Nostr client
 */
typedef struct nostr_NostrClient nostr_NostrClient;

/**
 * Opaque handle to Nostr keys (keypair)
 */
typedef struct nostr_NostrKeys nostr_NostrKeys;

/**
 * Callback invoked when a DM is received or sent (for history)
 *
 * # Parameters
 * - `sender_pubkey`: The sender's public key in npub format (must not be freed)
 * - `recipient_pubkey`: The recipient's public key in npub format (must not be freed)
 * - `content`: The message content (must not be freed)
 * - `timestamp`: Unix timestamp of the message
 * - `is_outgoing`: 1 if this is a message we sent, 0 if received
 * - `user_data`: User data passed to nostr_client_set_dm_callback
 */
typedef void (*nostr_NostrDmCallback)(const char *sender_pubkey,
                                      const char *recipient_pubkey,
                                      const char *content,
                                      uint64_t timestamp,
                                      int is_outgoing,
                                      void *user_data);

/**
 * Callback invoked when relay connection status changes
 *
 * # Parameters
 * - `relay_url`: The relay URL (must not be freed)
 * - `connected`: 1 if connected, 0 if disconnected
 * - `user_data`: User data passed to nostr_client_set_connect_callback
 */
typedef void (*nostr_NostrConnectCallback)(const char *relay_url, int connected, void *user_data);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a string allocated by this library
 *
 * # Safety
 * - `s` must be a pointer returned by a nostr_* function, or NULL
 */
void nostr_string_free(char *s);

/**
 * Generate a new random keypair
 *
 * # Returns
 * - Pointer to NostrKeys on success
 * - NULL on failure
 */
struct nostr_NostrKeys *nostr_keys_generate(void);

/**
 * Create keys from an nsec (bech32) or hex secret key
 *
 * # Parameters
 * - `secret_key`: The secret key in nsec1... or hex format
 *
 * # Returns
 * - Pointer to NostrKeys on success
 * - NULL on failure (invalid format)
 *
 * # Safety
 * - `secret_key` must be a valid null-terminated C string
 */
struct nostr_NostrKeys *nostr_keys_from_nsec(const char *secret_key);

/**
 * Get the public key in npub (bech32) format
 *
 * # Returns
 * - Newly allocated string that must be freed with nostr_string_free()
 * - NULL on failure
 *
 * # Safety
 * - `keys` must be a valid pointer from nostr_keys_generate or nostr_keys_from_nsec
 */
char *nostr_keys_npub(const struct nostr_NostrKeys *keys);

/**
 * Get the public key in hex format
 *
 * # Returns
 * - Newly allocated string that must be freed with nostr_string_free()
 * - NULL on failure
 *
 * # Safety
 * - `keys` must be a valid pointer from nostr_keys_generate or nostr_keys_from_nsec
 */
char *nostr_keys_pubkey_hex(const struct nostr_NostrKeys *keys);

/**
 * Get the secret key in nsec (bech32) format
 *
 * # Returns
 * - Newly allocated string that must be freed with nostr_string_free()
 * - NULL on failure
 *
 * # Safety
 * - `keys` must be a valid pointer from nostr_keys_generate or nostr_keys_from_nsec
 */
char *nostr_keys_nsec(const struct nostr_NostrKeys *keys);

/**
 * Free a NostrKeys instance
 *
 * # Safety
 * - `keys` must be a valid pointer from nostr_keys_generate or nostr_keys_from_nsec, or NULL
 */
void nostr_keys_free(struct nostr_NostrKeys *keys);

/**
 * Create a new Nostr client
 *
 * # Parameters
 * - `keys`: The keys to use for signing and decryption
 *
 * # Returns
 * - Pointer to NostrClient on success
 * - NULL on failure
 *
 * # Safety
 * - `keys` must be a valid pointer from nostr_keys_* functions
 */
struct nostr_NostrClient *nostr_client_new(const struct nostr_NostrKeys *keys);

/**
 * Add a relay to the client
 *
 * # Parameters
 * - `client`: The client instance
 * - `url`: The relay WebSocket URL (e.g., "wss://relay.damus.io")
 *
 * # Returns
 * - NOSTR_OK on success
 * - Error code on failure
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 * - `url` must be a valid null-terminated C string
 */
int nostr_client_add_relay(struct nostr_NostrClient *client, const char *url);

/**
 * Connect to all added relays and start listening for events
 *
 * # Parameters
 * - `client`: The client instance
 *
 * # Returns
 * - NOSTR_OK on success
 * - Error code on failure
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 */
int nostr_client_connect(struct nostr_NostrClient *client);

/**
 * Disconnect from all relays
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 */
void nostr_client_disconnect(struct nostr_NostrClient *client);

/**
 * Free a NostrClient instance
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new, or NULL
 */
void nostr_client_free(struct nostr_NostrClient *client);

/**
 * Set the callback for received DMs
 *
 * # Parameters
 * - `client`: The client instance
 * - `callback`: Function to call when a DM is received
 * - `user_data`: Opaque pointer passed to the callback
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 * - `callback` must be a valid function pointer
 * - `user_data` will be passed to callback; caller is responsible for its lifetime
 */
void nostr_client_set_dm_callback(struct nostr_NostrClient *client,
                                  nostr_NostrDmCallback callback,
                                  void *user_data);

/**
 * Set the callback for relay connection status changes
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 * - `callback` must be a valid function pointer
 */
void nostr_client_set_connect_callback(struct nostr_NostrClient *client,
                                       nostr_NostrConnectCallback callback,
                                       void *user_data);

/**
 * Get the file descriptor for event notification
 *
 * This fd becomes readable when there are pending events to process.
 * Use with poll(), select(), or g_io_add_watch().
 *
 * # Returns
 * - File descriptor on success
 * - -1 on failure
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 */
int nostr_client_get_fd(const struct nostr_NostrClient *client);

/**
 * Process pending events and invoke callbacks
 *
 * This should be called when the fd returned by nostr_client_get_fd() is readable.
 * All registered callbacks will be invoked synchronously from this function.
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 * - Must be called from the main thread (GLib main loop)
 */
void nostr_client_process_events(struct nostr_NostrClient *client);

/**
 * Send a NIP-17 private direct message
 *
 * # Parameters
 * - `client`: The client instance
 * - `recipient_pubkey`: The recipient's public key in hex or npub format
 * - `message`: The message content
 *
 * # Returns
 * - NOSTR_OK on success
 * - Error code on failure
 *
 * # Safety
 * - `client` must be a valid pointer from nostr_client_new
 * - `recipient_pubkey` and `message` must be valid null-terminated C strings
 */
int nostr_send_dm(struct nostr_NostrClient *client,
                  const char *recipient_pubkey,
                  const char *message);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace 
#endif  // __cplusplus

#endif  /* NOSTR_CORE_H */
